# Generated by Django 4.0.4 on 2022-07-04 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.client', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Biils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('sum', models.IntegerField()),
                ('date', models.DateField()),
                ('service', models.CharField(max_length=255)),
                ('fraud_score', models.FloatField()),
                ('service_class', models.IntegerField()),
                ('service_name', models.CharField(max_length=50)),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.client')),
                ('client_org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.organization', unique=True)),
            ],
        ),
    ]
